[build]
  command = "find netlify -maxdepth 2 -type f -o -type d | sort"
  publish = "public"

[dev]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
